{"cells":[{"cell_type":"markdown","metadata":{},"source":["# Working with Dictionaries - Lab\n","\n","## Introduction\n","Now that we know about dictionaries in Python, it is time to practice using them. In this lesson, you'll use your knowledge of dictionaries to retrieve and assign data about various cities.\n","\n","## Objectives\n","\n","You will be able to:\n","\n","* Assign values in a dictionary\n","* Access keys and values in a dictionary\n","\n","## Instructions\n","\n","Here is a dictionary representing the city of Greenville, North Carolina.  The area is in kilometers squared."]},{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[],"source":["greenville = {'Area': 68, 'City': 'Greenville', 'Country': 'USA', 'Population': 84554}"]},{"cell_type":"markdown","metadata":{},"source":["> Remember to press shift + enter to run the code.\n","\n","Let's retrieve the population of the city and assign it to the variable `greenville_population`."]},{"cell_type":"code","execution_count":3,"metadata":{},"outputs":[{"data":{"text/plain":["84554"]},"execution_count":3,"metadata":{},"output_type":"execute_result"}],"source":["greenville_population = greenville['Population']\n","greenville_population"]},{"cell_type":"markdown","metadata":{},"source":["Now retrieve the area of Greenville and assign it to the variable `greenville_area`."]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[{"data":{"text/plain":["68"]},"execution_count":4,"metadata":{},"output_type":"execute_result"}],"source":["greenville_area = greenville['Area']\n","greenville_area # 68"]},{"cell_type":"markdown","metadata":{},"source":["Now let's take a look at all of the keys in the `greenville` dictionary and coerce them into a list.  Assign this variable to the list `city_keys`."]},{"cell_type":"code","execution_count":6,"metadata":{},"outputs":[{"data":{"text/plain":["['Area', 'City', 'Country', 'Population']"]},"execution_count":6,"metadata":{},"output_type":"execute_result"}],"source":["city_keys = list(greenville.keys())\n","city_keys # ['Area', 'City', 'Country', 'Population']"]},{"cell_type":"markdown","metadata":{},"source":["Alright, next let's get all of the values in our greenville dictionary and coerce it into a list.  Assign that list to the variable `city_values`."]},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[{"data":{"text/plain":["[68, 'Greenville', 'USA', 84554]"]},"execution_count":7,"metadata":{},"output_type":"execute_result"}],"source":["city_values = list(greenville.values())\n","city_values # [68, 'Greenville', 'USA', 84554]"]},{"cell_type":"markdown","metadata":{},"source":["## Working with multiple cities\n","\n","We can retrieve our data from an excel or Google sheet like the one [shown here](https://docs.google.com/spreadsheets/d/1BTJMMFH9t4p5UmHj5kiC6PGfMN6yaaaZkocx0mDqTK0/edit#gid=0) named Travel Cities and Countries.\n","\n","![](https://curriculum-content.s3.amazonaws.com/data-science/images/countries-cities.png)\n","\n","Luckily for us, we already have the spreadsheet downloaded and located in the current folder.  You can find the file (`cities.xlsx`) in this lesson's GitHub repository. Next, we will use a library called **Pandas** to get this data from the excel file into Python code. We already have the code for reading an excel file into Python written for us below. Let's check it out.\n","\n","> **Note:** To import a library or module in Python, we do so by writing `import` followed by the name of the thing we want to import. We can optionally include an *alias* for our import, which is done by writing **as** after the name of the thing we are importing followed by the name we would like to use for our *alias*. **Do not worry** about aliases right now. Just know that the *convention* for importing the Pandas library is to import it and alias it as `pd` like we see below.   \n","We'll talk about packages and Pandas specifically in much more detail soon enough!"]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Collecting numpy\n","  Downloading numpy-2.0.1-cp311-cp311-macosx_10_9_x86_64.whl (21.2 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m21.2/21.2 MB\u001b[0m \u001b[31m567.3 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n","\u001b[?25hCollecting pandas\n","  Downloading pandas-2.2.2-cp311-cp311-macosx_10_9_x86_64.whl (12.6 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m12.6/12.6 MB\u001b[0m \u001b[31m1.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0mm\n","\u001b[?25hRequirement already satisfied: python-dateutil>=2.8.2 in /Users/djwizz/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)\n","Collecting pytz>=2020.1\n","  Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m505.5/505.5 kB\u001b[0m \u001b[31m685.1 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n","\u001b[?25hCollecting tzdata>=2022.7\n","  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m345.4/345.4 kB\u001b[0m \u001b[31m327.5 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n","\u001b[?25hRequirement already satisfied: six>=1.5 in /Users/djwizz/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n","Installing collected packages: pytz, tzdata, numpy, pandas\n","Successfully installed numpy-2.0.1 pandas-2.2.2 pytz-2024.1 tzdata-2024.1\n","\n","\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n","\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip3 install --upgrade pip\u001b[0m\n","Note: you may need to restart the kernel to use updated packages.\n"]}],"source":["pip install numpy pandas"]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[{"ename":"ImportError","evalue":"Unable to import required dependencies:\nnumpy: \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.8 from \"/opt/anaconda3/envs/learn-env/bin/python\"\n  * The NumPy version is: \"1.19.1\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: dlopen(/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libopenblas.dylib\n  Referenced from: <7D231C5E-1A92-3007-BEB3-CAF306EC338A> /opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so\n  Reason: tried: '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/bin/../lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/bin/../lib/libopenblas.dylib' (no such file), '/usr/local/lib/libopenblas.dylib' (no such file), '/usr/lib/libopenblas.dylib' (no such file, not in dyld cache)\n","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-cd755be98823>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mfile_name\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'./cities.xlsx'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mtravel_df\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_excel\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mcities\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtravel_df\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mto_dict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'records'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/pandas/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mmissing_dependencies\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 16\u001b[0;31m     raise ImportError(\n\u001b[0m\u001b[1;32m     17\u001b[0m         \u001b[0;34m\"Unable to import required dependencies:\\n\"\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m\"\\n\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmissing_dependencies\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     18\u001b[0m     )\n","\u001b[0;31mImportError\u001b[0m: Unable to import required dependencies:\nnumpy: \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.8 from \"/opt/anaconda3/envs/learn-env/bin/python\"\n  * The NumPy version is: \"1.19.1\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: dlopen(/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libopenblas.dylib\n  Referenced from: <7D231C5E-1A92-3007-BEB3-CAF306EC338A> /opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so\n  Reason: tried: '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/numpy/core/../../../../libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/bin/../lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/envs/learn-env/lib/libopenblas.dylib' (no such file), '/opt/anaconda3/envs/learn-env/bin/../lib/libopenblas.dylib' (no such file), '/usr/local/lib/libopenblas.dylib' (no such file), '/usr/lib/libopenblas.dylib' (no such file, not in dyld cache)\n"]}],"source":["\n","import pandas as pd\n","file_name = './cities.xlsx'\n","travel_df = pd.read_excel(file_name)\n","cities = travel_df.to_dict('records')"]},{"cell_type":"markdown","metadata":{},"source":["> Remember to press shift + enter.\n","\n","Great! We just used Pandas to read the data from our excel file and turn each row of data into a dictionary. Again, don't worry about exactly how Pandas is doing this, but know that Pandas is a great tool when trying to accomplish a task such as turning data from an excel file into data we can use in Python.\n","\n","Run the cell below to see what our data looks like now."]},{"cell_type":"code","execution_count":13,"metadata":{},"outputs":[{"data":{"text/plain":["[{'City': 'Solta', 'Country': 'Croatia', 'Population': 1700, 'Area': 59},\n"," {'City': 'Greenville', 'Country': 'USA', 'Population': 84554, 'Area': 68},\n"," {'City': 'Buenos Aires',\n","  'Country': 'Argentina',\n","  'Population': 13591863,\n","  'Area': 4758},\n"," {'City': 'Los Cabos',\n","  'Country': 'Mexico',\n","  'Population': 287651,\n","  'Area': 3750},\n"," {'City': 'Walla Walla Valley',\n","  'Country': 'USA',\n","  'Population': 32237,\n","  'Area': 33},\n"," {'City': 'Marakesh', 'Country': 'Morocco', 'Population': 928850, 'Area': 200},\n"," {'City': 'Albuquerque',\n","  'Country': 'New Mexico',\n","  'Population': 559277,\n","  'Area': 491},\n"," {'City': 'Archipelago Sea',\n","  'Country': 'Finland',\n","  'Population': 60000,\n","  'Area': 8300},\n"," {'City': 'Iguazu Falls',\n","  'Country': 'Argentina',\n","  'Population': 0,\n","  'Area': 672},\n"," {'City': 'Salina Island', 'Country': 'Italy', 'Population': 4000, 'Area': 27},\n"," {'City': 'Toronto', 'Country': 'Canada', 'Population': 630, 'Area': 2731571},\n"," {'City': 'Pyeongchang',\n","  'Country': 'South Korea',\n","  'Population': 2581000,\n","  'Area': 3194}]"]},"execution_count":13,"metadata":{},"output_type":"execute_result"}],"source":["cities"]},{"cell_type":"markdown","metadata":{},"source":["Now we will work with reading and manipulating this list of dictionaries, `cities`.\n","\n","### Working with our list of cities\n","\n","First, access the third to last element and set it equal to the variable `salina`."]},{"cell_type":"code","execution_count":15,"metadata":{},"outputs":[],"source":["salina = None \n","salina\n","# {'Area': 27, 'City': 'Salina Island', 'Country': 'Italy', 'Population': 4000}"]},{"cell_type":"markdown","metadata":{},"source":["Now access the fourth city in the list, and set its population equal to a variable called `los_cabos_pop`."]},{"cell_type":"code","execution_count":17,"metadata":{},"outputs":[],"source":["los_cabos_pop = None\n","los_cabos_pop # 287651"]},{"cell_type":"markdown","metadata":{},"source":["Now calculate the number of cities in the list and assign the number to the variable `city_count`."]},{"cell_type":"code","execution_count":19,"metadata":{"scrolled":true},"outputs":[],"source":["city_count = None\n","city_count # 12"]},{"cell_type":"markdown","metadata":{},"source":["Finally, change the spelling of the South Korean city, Pyeongchang, to the string `'PyeongChang'`, its alternative spelling."]},{"cell_type":"code","execution_count":21,"metadata":{},"outputs":[],"source":["cities[11]['City'] = None\n","cities[11]['City'] # 'PyeongChang'"]},{"cell_type":"markdown","metadata":{},"source":["Now let's work on retrieving a collection of information about a dictionary.  Use the appropriate dictionary method to return a list of values in the dictionary regarding Pyeongchang.  Assign the list to the variable `pyeongchang_values`."]},{"cell_type":"code","execution_count":27,"metadata":{},"outputs":[],"source":["pyeongchang_values = None\n","\n","pyeongchang_values # ['PyeongChang', 'South Korea', 2581000, 3194]\n","type(pyeongchang_values) # list"]},{"cell_type":"markdown","metadata":{},"source":["And now set `pyeongchang_keys` equal to a list of keys in the dictionary regarding Pyeongchang."]},{"cell_type":"code","execution_count":28,"metadata":{},"outputs":[],"source":["pyeongchang_keys = None\n","\n","\n","pyeongchang_keys # ['City', 'Country', 'Population', 'Area']\n","type(pyeongchang_keys) # list"]},{"cell_type":"markdown","metadata":{},"source":["## Summary\n","\n","In this section, we saw how to assign, retrieve, and re-assign data in a dictionary.  We saw how we can retrieve a collection of information from a dictionary, like a list of its keys and values, and we saw how we can work with a list of dictionaries."]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.1"}},"nbformat":4,"nbformat_minor":2}
